services:
  - type: web
    name: walletsite
    env: python
    rootDir: .
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: bash -lc "python manage.py migrate --noinput || (sleep 5 && python manage.py migrate --noinput); gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers=1 --timeout 120 --log-file -"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com,https://localhost,http://localhost,http://127.0.0.1
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: WEB_CONCURRENCY
        value: '3'
      - key: DATABASE_URL
        fromDatabase:
          name: walletsite-postgres
          property: connectionString
    healthCheckPath: /admin/login/

databases:
  - name: walletsite-postgres
    plan: free
    region: oregon
    databaseName: walletsite
    user: walletsite
